---
kind: pipeline
name: argos-release
type: docker

steps:
  - name: check license
    image: argosnotary/argos-build:3.6.3
    commands:
    - mvn license:check
 
  - name: build integrated snapshot image
    image: plugins/docker
    settings:
      context: docker
      dockerfile: docker/Dockerfile
      repo: argosnotary/argos-snapshot
      tags: ${DRONE_TAG:-${DRONE_BRANCH//\//_}}
      build_args:
        - ARGOS_VERSION=0.0.1-RC6
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token
    when:
      event:
        - push
    depends_on:
    - check license
    
  - name: argossnashot
    image: curlimages/curl
    pull: always
    when:
      event:
        - push
    depends_on:
    - build integrated snapshot image
  
  - name: test snapshot image
    image: curlimages/curl
    pull: always
    commands:
    - curl --retry-connrefused --retry 10 --retry-delay 0 -u admin:admin "http://argos"
    - curl --retry-connrefused --retry 10 --retry-delay 0 -u admin:admin -k "https://argos"
    - curl --retry-connrefused --retry 10 --retry-delay 0 -u admin:admin "http://argos:8080/actuator/health"
    - curl --retry-connrefused --retry 10 --retry-delay 0 -u admin:admin "http://argos:8087"
    depends_on:
    - argos
    when:
      event:
        - push
        
  - name: build helm snapshot chart
    image: argosnotary/argos-build:3.6.3
    environment:
      HELM_EXPERIMENTAL_OCI: 1
    commands:
    - cd helm/charts
    - helm chart save argos/ "argosnotary/argos-chart-snapshot:${DRONE_TAG:-${DRONE_BRANCH//\//_}}"
    - helm chart push "argosnotary/argos-chart-snapshot:${DRONE_TAG:-${DRONE_BRANCH//\//_}}"
    when:
      event:
        - push
    depends_on:
    - check license
        
  - name: build and release integrated image
    image: plugins/docker
    settings:
      context: docker
      dockerfile: docker/Dockerfile
      repo: argosnotary/argos
      auto_tag: true
      build_args:
        - ARGOS_VERSION=${DRONE_TAG}
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token
    when:
      event:
        - tag
    depends_on:
    - check license
    
  - name: argos
    image: curlimages/curl
    pull: always
    when:
      event:
        - tag
    depends_on:
    - build and release integrated image
  
  - name: test image
    image: curlimages/curl
    pull: always
    commands:
    - curl --retry-connrefused --retry 10 --retry-delay 0 -u admin:admin "http://argos"
    - curl --retry-connrefused --retry 10 --retry-delay 0 -u admin:admin "http://argos:8080/actuator/health"
    - curl --retry-connrefused --retry 10 --retry-delay 0 -u admin:admin "http://argos:8087"
    depends_on:
    - argos
    when:
      event:
        - tag
        
  - name: build helm and release chart
    image: argosnotary/argos-build:3.6.3
    environment:
      HELM_EXPERIMENTAL_OCI: 1
    commands:
    - cd helm/charts
    - helm chart save argos/ "argosnotary/argos-chart:${DRONE_TAG}"
    - helm chart save argos/ argosnotary/argos-chart:latest
    - helm chart push "argosnotary/argos-chart:${DRONE_TAG}"
    - helm chart save argos/ argosnotary/argos-chart:latest
    when:
      event:
        - tag
    depends_on:
    - check license
      
trigger:
  event:
    - push
    - tag

